# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CenveroCetus < Formula
  desc "HTML to video renderer - self-contained, deterministic, fast"
  homepage "https://cetus.cenvero.org"
  version "0.3.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cenvero/cetus/releases/download/v0.3.0/cetus_v0.3.0_darwin_amd64.tar.gz"
      sha256 "bf7bdbcbf269233d09a7f98eae20eb66057fe1d5bd23b182f9ca6460d8559f24"

      define_method(:install) do
        bin.install "cetus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cenvero/cetus/releases/download/v0.3.0/cetus_v0.3.0_darwin_arm64.tar.gz"
      sha256 "9e236a7da3d27ee86ca73dfcf25446a9f1216cd36c809e52278c6436826b6fe1"

      define_method(:install) do
        bin.install "cetus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cenvero/cetus/releases/download/v0.3.0/cetus_v0.3.0_linux_amd64.tar.gz"
      sha256 "32223134a3564a3a105ec712579ab1210d4b710fd10255852f4c863560adadbc"
      define_method(:install) do
        bin.install "cetus"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cetus version")
  end
end
